import { Activity } from './types';

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '1',
    title: 'Bike Trip to Hills',
    category: 'Outdoor & Active',
    time: 'Today at 6:00 PM',
    attendees: 12,
    lat: 28.4744,
    lng: 77.503,
    icon: '🚴',
    userAvatar: 'https://picsum.photos/seed/user1/100/100',
    userName: 'Arnav',
    description: 'A moderate-paced bike ride to the nearby hills. All skill levels welcome!'
  },
  {
    id: '2',
    title: 'Marine Drive Sunset Walk',
    category: 'Outdoor & Active',
    time: 'Today at 6:30 PM',
    attendees: 45,
    lat: 18.944,
    lng: 72.823,
    icon: '🌅',
    userAvatar: 'https://picsum.photos/seed/user2/100/100',
    userName: 'Priya',
    description: 'Enjoying the iconic Mumbai sunset at Marine Drive.'
  },
  {
    id: '3',
    title: 'Cubbon Park Yoga',
    category: 'Outdoor & Active',
    time: 'Tomorrow at 7:00 AM',
    attendees: 20,
    lat: 12.976,
    lng: 77.594,
    icon: '🧘',
    userAvatar: 'https://picsum.photos/seed/user3/100/100',
    userName: 'Rahul',
    description: 'Morning yoga session in the green heart of Bangalore.'
  },
  {
    id: '4',
    title: 'Victoria Memorial Photo Walk',
    category: 'Popular',
    time: 'Saturday at 4:00 PM',
    attendees: 15,
    lat: 22.544,
    lng: 88.342,
    icon: '📸',
    userAvatar: 'https://picsum.photos/seed/user4/100/100',
    userName: 'Sanya',
    description: 'Capturing the architectural beauty of Kolkata.'
  },
  {
    id: '5',
    title: 'Marina Beach Volleyball',
    category: 'Outdoor & Active',
    time: 'Sunday at 5:00 PM',
    attendees: 10,
    lat: 13.05,
    lng: 80.282,
    icon: '🏐',
    userAvatar: 'https://picsum.photos/seed/user5/100/100',
    userName: 'Vikram',
    description: 'Friendly beach volleyball match in Chennai.'
  },
  {
    id: '6',
    title: 'Charminar Food Crawl',
    category: 'Food & Drinks',
    time: 'Today at 8:00 PM',
    attendees: 30,
    lat: 17.361,
    lng: 78.474,
    icon: '🌮',
    userAvatar: 'https://picsum.photos/seed/user6/100/100',
    userName: 'Ananya',
    description: 'Exploring the legendary street food of Old Hyderabad.'
  },
  {
    id: '7',
    title: 'Amer Fort Sunrise Trek',
    category: 'Travel',
    time: 'Tomorrow at 5:30 AM',
    attendees: 8,
    lat: 26.985,
    lng: 75.851,
    icon: '🏰',
    userAvatar: 'https://picsum.photos/seed/user7/100/100',
    userName: 'Kabir',
    description: 'Trekking to the hills near Amer Fort for a stunning Jaipur sunrise.'
  },
  {
    id: '8',
    title: 'Ganga Aarti Gathering',
    category: 'Popular',
    time: 'Today at 6:45 PM',
    attendees: 100,
    lat: 25.317,
    lng: 83.006,
    icon: '🕯️',
    userAvatar: 'https://picsum.photos/seed/user8/100/100',
    userName: 'Aditi',
    description: 'Witnessing the spiritual Ganga Aarti at Dashashwamedh Ghat, Varanasi.'
  },
  {
    id: '9',
    title: 'Sabarmati Riverfront Cycling',
    category: 'Outdoor & Active',
    time: 'Saturday at 6:00 AM',
    attendees: 12,
    lat: 23.022,
    lng: 72.571,
    icon: '🚴',
    userAvatar: 'https://picsum.photos/seed/user9/100/100',
    userName: 'Ishaan',
    description: 'Morning cycling along the beautiful Sabarmati Riverfront in Ahmedabad.'
  },
  {
    id: '10',
    title: 'Rock Garden Exploration',
    category: 'Travel',
    time: 'Sunday at 11:00 AM',
    attendees: 25,
    lat: 30.752,
    lng: 76.81,
    icon: '🗿',
    userAvatar: 'https://picsum.photos/seed/user10/100/100',
    userName: 'Meera',
    description: 'Discovering the unique sculptures at the Rock Garden, Chandigarh.'
  },
  {
    id: '11',
    title: 'Upper Lake Sunset Cruise',
    category: 'Travel',
    time: 'Today at 5:30 PM',
    attendees: 18,
    lat: 23.25,
    lng: 77.35,
    icon: '⛵',
    userAvatar: 'https://picsum.photos/seed/user11/100/100',
    userName: 'Aman',
    description: 'A relaxing boat ride on the scenic Upper Lake of Bhopal.'
  },
  {
    id: '12',
    title: 'Van Vihar Safari',
    category: 'Outdoor & Active',
    time: 'Tomorrow at 9:00 AM',
    attendees: 12,
    lat: 23.23,
    lng: 77.37,
    icon: '🦁',
    userAvatar: 'https://picsum.photos/seed/user12/100/100',
    userName: 'Neha',
    description: 'Exploring the wildlife at Van Vihar National Park.'
  },
  {
    id: '13',
    title: 'Bhopali Poha Breakfast',
    category: 'Food & Drinks',
    time: 'Sunday at 8:30 AM',
    attendees: 25,
    lat: 23.26,
    lng: 77.41,
    icon: '🥣',
    userAvatar: 'https://picsum.photos/seed/user13/100/100',
    userName: 'Zaid',
    description: 'The best Poha-Jalebi breakfast in the old city area.'
  },
  {
    id: '14',
    title: 'DB Mall Shopping Spree',
    category: 'Popular',
    time: 'Saturday at 4:00 PM',
    attendees: 50,
    lat: 23.233,
    lng: 77.43,
    icon: '🛍️',
    userAvatar: 'https://picsum.photos/seed/user14/100/100',
    userName: 'Kriti',
    description: 'Weekend shopping and food court hangout at DB Mall.'
  },
  {
    id: '15',
    title: 'Sanchi Stupa Day Trip',
    category: 'Travel',
    time: 'Sunday at 7:00 AM',
    attendees: 15,
    lat: 23.48,
    lng: 77.74,
    icon: '☸️',
    userAvatar: 'https://picsum.photos/seed/user15/100/100',
    userName: 'Arjun',
    description: 'A historical journey to the ancient Sanchi Stupa.'
  },
  {
    id: '16',
    title: 'Bharat Bhavan Art Walk',
    category: 'Popular',
    time: 'Today at 6:00 PM',
    attendees: 10,
    lat: 23.25,
    lng: 77.39,
    icon: '🎨',
    userAvatar: 'https://picsum.photos/seed/user16/100/100',
    userName: 'Siddharth',
    description: 'Exploring contemporary Indian art at Bharat Bhavan.'
  },
  {
    id: '17',
    title: 'Kerwa Dam Picnic',
    category: 'Outdoor & Active',
    time: 'Tomorrow at 11:00 AM',
    attendees: 20,
    lat: 23.18,
    lng: 77.36,
    icon: '🧺',
    userAvatar: 'https://picsum.photos/seed/user17/100/100',
    userName: 'Tanvi',
    description: 'A fun picnic day at the serene Kerwa Dam.'
  },
  {
    id: '18',
    title: 'Manuabhan Tekri Trek',
    category: 'Outdoor & Active',
    time: 'Sunday at 6:00 AM',
    attendees: 14,
    lat: 23.28,
    lng: 77.38,
    icon: '⛰️',
    userAvatar: 'https://picsum.photos/seed/user18/100/100',
    userName: 'Rohan',
    description: 'Early morning trek to the Tekri for a panoramic view of Bhopal.'
  }
];

export const CATEGORIES = ["All", "Popular", "Travel", "Outdoor & Active", "Nightlife", "Food & Drinks"];
